name: Deploy Raccoon Bot (Dual Server)

on:
  push:
    branches:
      - main  # Сработает при пуше в ветку main

jobs:
  # Деплой на НОВЫЙ сервер (ветка main)
  deploy-new:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to NEW Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_NEW }}
          script: |
            # 1. Штатно останавливаем службу
            sudo systemctl stop raccoon_bot || true
            # 2. Добиваем любые зависшие процессы бота
            sudo pkill -f bot.py || true
            
            cd ~/Raccoon_life
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # 3. Запускаем чистую службу
            sudo systemctl start raccoon_bot