name: Deploy Old Server Bot

on:
  push:
    branches:
      - old-server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Обновили с v3 на v4
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        # Рекомендую также проверить наличие v3 или выше для ssh-action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_NEW }}
          script: |
            cd ~/Raccoon_life_test
            git fetch origin old-server
            git reset --hard origin/old-server
            
            # Активируем venv и обновляем зависимости
            source venv/bin/activate
            pip install python-telegram-bot python-dotenv requests
            
            # Перезапуск сервиса
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart raccoon-test